// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpCZ6hj2_Lg5P1o_hZN0bu8Qtc7cftik',
    appId: '1:259757448182:web:fa0649b37db79e8f0bc5d7',
    messagingSenderId: '259757448182',
    projectId: 'motapp-43a31',
    authDomain: 'motapp-43a31.firebaseapp.com',
    storageBucket: 'motapp-43a31.firebasestorage.app',
    measurementId: 'G-EK7SC6HXPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTC0fTNGkRFKtneAEVRbQeyZ5Ngpt2VU',
    appId: '1:259757448182:android:a00edabe8437149d0bc5d7',
    messagingSenderId: '259757448182',
    projectId: 'motapp-43a31',
    storageBucket: 'motapp-43a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DJD0FS623CooLW3KqpWmkqF9LdDSbyM',
    appId: '1:259757448182:ios:b44731078e78a9ac0bc5d7',
    messagingSenderId: '259757448182',
    projectId: 'motapp-43a31',
    storageBucket: 'motapp-43a31.firebasestorage.app',
    iosBundleId: 'br.com.vilasboas.motapp',
  );
}
